import { AuthProvider } from "../context/AuthContext"; // <-- Impor
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ 
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider> {/* <-- Bungkus di sini */}
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}